version: "3"
services:
    web:
        image: nginx
        volumes:
            - "./etc/nginx.conf:/etc/nginx/conf.d/default.conf"
            - "./etc/letsencrypt:/etc/letsencrypt:cached"
            - "../:/usr/share/nginx:cached"
        ports:
            - "8000:80"
            - "3000:443"
        restart: always
        depends_on:
            - php
    php:
        image: serh/docker-php73dev
        restart: always
        container_name: php
        #       command: /bin/sh -c "cd /usr/share/nginx; php artisan config:cache;"
        volumes:
            - "./etc/php/php.ini-development:/usr/local/etc/php/php.ini:cached"
            - "../:/usr/share/nginx:cached"

    redis:
        image: redis
        restart: always
        container_name: redis-cache

    push:
        image: serh/docker-laravel-echo-server
        restart: always
        container_name: push
        ports:
            - "6001:6001"
        environment:
            - REDIS_HOST=redis-cache

    mysql:
        image: mysql:5.7
        container_name: mysql
        restart: always
        env_file:
            - "./.env"
        environment:
            - MYSQL_DATABASE=${DB_DATABASE}
            - MYSQL_USER=${DB_USERNAME}
            - MYSQL_PASSWORD=${DB_PASSWORD}
            - MYSQL_ROOT_PASSWORD=${DB_ROOTPASS}
  
        ports:
            - "3306:3306"
        volumes:
            - "./db/mysql:/var/lib/mysql:cached"
